[package]
name = "advent-2021"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "~1.0.51"
aoc-runner = "^0.3.0"
aoc-runner-derive = "^0.3.0"
itertools = "^0.10.1"
nom = "~7.1.0"
thiserror = "~1.0.30"
